
import java.util.ArrayList;


/**
 * @Author: Oscar Juarez y Rodrigo Zea
 * @Version: 22.09.17
 * Programacion Orientada a objetos
 * Descripcion: Clase o form encargada de desplegar el resumen de datos que el usuario especifico en el resumen del programa
 */
public class informacionTrabajadores extends javax.swing.JFrame {
    public static boolean controlT;
    public static Medico[][] matrizMe;
    public static Enfermera[][] matrizEn;
    public static ArrayList<Medico> listaGuardiaM = new ArrayList<Medico>();
    public static ArrayList<Enfermera> listaGuardiaE = new ArrayList<Enfermera>();
    Calculos calc = new Calculos();
    private String nombreIM;
    private int turnosIM;
    private double salarioIM, totalIM, adicional;
    
    /**
     * Creates new form informacionTrabajadores
     */
    public informacionTrabajadores() {
        initComponents();
    }
    
    /**
     * Constructor con parametros indicados, basicamente pasa la lista de trabajadores con sus turnos
     * @param matrizM: matriz de los medicos
     * @param matrizE: matriz de las enfermeras
     * @param lgM: Lista de los medicos
     * @param lgE: lista de las enfermeras
     */
    public informacionTrabajadores(Medico[][] matrizM, Enfermera[][] matrizE, ArrayList<Medico> lgM, ArrayList<Enfermera> lgE){ 
        initComponents();
        matrizMe = matrizM;
        matrizEn = matrizE;
        listaGuardiaM = lgM;
        listaGuardiaE = lgE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        medicosBtn = new javax.swing.JComboBox<>();
        enfermerasBtn = new javax.swing.JComboBox<>();
        conDatosBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        parejasTA = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        adicionalLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nomLbl = new javax.swing.JLabel();
        extLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        trnLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Ver informacion de trabajadores (Anualmente)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enfermera intensivista que mas turnos trabajo:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Salario Total:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad de veces que una pareja ha trabajado:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Seleccione el nombre del medico:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Seleccione el nombre de la enfermera:");

        medicosBtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juan Perez", "Guadalupe Torres"}));

        enfermerasBtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lidia Mendez", "Lorna Suarez" }));

        conDatosBtn.setText("Consultar Datos");
        conDatosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conDatosBtnActionPerformed(evt);
            }
        });

        parejasTA.setEditable(false);
        parejasTA.setColumns(20);
        parejasTA.setRows(5);
        jScrollPane1.setViewportView(parejasTA);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total adicional a pagar por turnos de guardia:");

        adicionalLbl.setText("Q");

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nomLbl.setText("Nombre");

        extLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        extLbl.setText("Salario");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Turnos:");

        trnLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        trnLbl.setText("Turnos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(extLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trnLbl))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(conDatosBtn)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(31, 31, 31)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(medicosBtn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(enfermerasBtn, 0, 167, Short.MAX_VALUE)))))
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(adicionalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomLbl)
                    .addComponent(jLabel9)
                    .addComponent(trnLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(extLbl))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(medicosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(enfermerasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conDatosBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adicionalLbl)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conDatosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conDatosBtnActionPerformed
        int contar;
        
        contar = calc.contarVeces(matrizMe, matrizEn, (String) medicosBtn.getSelectedItem(), (String) enfermerasBtn.getSelectedItem());
        parejasTA.setText("El numero de veces que esta" + "\npareja ha trabajado es de: \n\n" + String.valueOf(contar) + " veces");
    }//GEN-LAST:event_conDatosBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        parejasTA.setLineWrap(true);
        calculoIntensivista();
        adicional();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pantallaPrincipal pantalla = new pantallaPrincipal();
        this.setVisible(false);
        pantalla.setVisible(true);
        
        pantalla.listaPantallaM = listaGuardiaM;
        pantalla.listaPantallaE = listaGuardiaE;
        pantalla.matrizPantallaM = matrizMe;
        pantalla.matrizPantallaE = matrizEn;
        pantalla.variableControl = controlT;
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Calcula y despliega los datos requeridos por desplegar de la enfermera intensivista que mas turnos trabajo
     */
    public void calculoIntensivista(){
        
        turnosIM = calc.intensivistaMasTurnos(matrizEn, listaGuardiaE);
        nombreIM = calc.nombreIntensivista(listaGuardiaE, turnosIM);
        salarioIM = calc.SalarioIntensivista(listaGuardiaE, turnosIM);
        totalIM = calc.SalarioExtraIntensivista(turnosIM, salarioIM);
        
        nomLbl.setText(nombreIM);
        trnLbl.setText(turnosIM+"");
        extLbl.setText("Q"+totalIM+"");
               
    }
    
    /**
     * Calcula y despliega el total a pagar por turnos extras de los trabajadores
     */
    public void adicional(){
        adicional = calc.devengado(listaGuardiaM, listaGuardiaE);
        adicionalLbl.setText("Q"+adicional+"");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informacionTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informacionTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informacionTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacionTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informacionTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adicionalLbl;
    private javax.swing.JButton conDatosBtn;
    private javax.swing.JComboBox<String> enfermerasBtn;
    private javax.swing.JLabel extLbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> medicosBtn;
    private javax.swing.JLabel nomLbl;
    private javax.swing.JTextArea parejasTA;
    private javax.swing.JLabel trnLbl;
    // End of variables declaration//GEN-END:variables
}
