
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * @Author: Oscar Juarez y Rodrigo Zea
 * @Version: 22.09.17
 * Programacion Orientada a objetos
 * Descripcion: 
 *
*/
public class pantallaPrincipal extends javax.swing.JFrame {

    Calculos calculos = new Calculos();
    public static boolean variableControl;
    public static Medico[][] matrizPantallaM;
    public static Enfermera[][] matrizPantallaE;
    resumenGuardias pantallaResumen = new resumenGuardias();
    public static ArrayList<Medico> listaPantallaM = new ArrayList<Medico>();
    public static ArrayList<Enfermera> listaPantallaE = new ArrayList<Enfermera>();
    
    public pantallaPrincipal() {
        initComponents();
        variableControl = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AsignarTurnosBtn = new javax.swing.JButton();
        verTurnosBtn = new javax.swing.JButton();
        verTurnosBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu Principal");

        AsignarTurnosBtn.setText("Asignar Turnos");
        AsignarTurnosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarTurnosBtnActionPerformed(evt);
            }
        });

        verTurnosBtn.setText("Ver y editar turnos");
        verTurnosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTurnosBtnActionPerformed(evt);
            }
        });

        verTurnosBtn1.setText("Consultar datos");
        verTurnosBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTurnosBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AsignarTurnosBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verTurnosBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verTurnosBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(AsignarTurnosBtn)
                .addGap(18, 18, 18)
                .addComponent(verTurnosBtn)
                .addGap(18, 18, 18)
                .addComponent(verTurnosBtn1)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsignarTurnosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarTurnosBtnActionPerformed
        calculos.asignarTurnos(matrizPantallaM, matrizPantallaE, listaPantallaM, listaPantallaE);
        JOptionPane.showMessageDialog(this, "Turnos generados con exito!");
    }//GEN-LAST:event_AsignarTurnosBtnActionPerformed

    private void verTurnosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTurnosBtnActionPerformed
        this.setVisible(false);
        resumenGuardias pantalla = new resumenGuardias();
        pantalla.setVisible(true);
    }//GEN-LAST:event_verTurnosBtnActionPerformed

    private void verTurnosBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTurnosBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verTurnosBtn1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           
        if (variableControl) {
            
            matrizPantallaM = new Medico[12][31];
            matrizPantallaE = new Enfermera[12][31];

            Medico medico1 = new Medico("Juan Perez", "1234567870101" ,"6799652-3", 15000, 0, true, "89098");
            Medico medico2 = new Medico("Luis Gutierrez", " 9876543260101" ," 8964547-3", 12000, 0, false, "98554");
            Medico medico3 = new Medico("Eduardo Gonzalez", "5642871750101" ," 8786456-6", 17000, 0, true, "5653");
            Medico medico4 = new Medico("Guadalupe Torres", "4562973920101" ,"5684873-1", 17000, 0, true, "10098");
            Medico medico5 = new Medico("Maria Castillo", "569395290101" ,"8765485-7", 13000, 0, false, "67965");

            Enfermera enfermera1 = new Enfermera("Juana Lopez", "5643213450101", " 563269-K", 6000, 0, false, 2);
            Enfermera enfermera2 = new Enfermera("Lidia Mendez", "1246547850101", "7654376-6", 9000, 0, true, 2);
            Enfermera enfermera3 = new Enfermera("Miriam Garcia", "6547854370101", "9876456-8", 8000, 0, false, 14);
            Enfermera enfermera4 = new Enfermera("Lorna Suarez", "569374160101", "4567865-8", 10000, 0, true, 12);
            Enfermera enfermera5 = new Enfermera("Mariela Rodriguez", "3254786540101", "6789654-8", 8000, 0, false, 2);

            listaPantallaM.add(medico1);
            listaPantallaM.add(medico2);
            listaPantallaM.add(medico3);
            listaPantallaM.add(medico4);
            listaPantallaM.add(medico5);

            listaPantallaE.add(enfermera1);        
            listaPantallaE.add(enfermera2);
            listaPantallaE.add(enfermera3);
            listaPantallaE.add(enfermera4);
            listaPantallaE.add(enfermera5);
            
            variableControl = false;
        }
        
        pantallaResumen.listaGuardiaM = listaPantallaM;
        pantallaResumen.listaGuardiaE = listaPantallaE;
        pantallaResumen.matrizGuardiaM = matrizPantallaM;
        pantallaResumen.matrizGuardiaE = matrizPantallaE;
        pantallaResumen.controlGuardia = variableControl;
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsignarTurnosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton verTurnosBtn;
    private javax.swing.JButton verTurnosBtn1;
    // End of variables declaration//GEN-END:variables
}
